### ISSUE TITLE
Developing the wheel once again, huh?

### ISSUE THREAD

**Issue by Szybet** [Jayy001/RmAnki#3]
Hello
well
https://github.com/Szybet/sanki
What about working together, instead of creating basically the same thing?

**Comment by Jayy001** [comment]
Hi, thanks for creating an issue - with all due respect, this software is not "basically the same thing". 

This is specifically designed for the remarkable device, using its proper libraries. In contrast, your project is geared towards the Kobo (it was stated on the README that it hasn't been tested on any other devices, so how would you know it even works?), and the UI design is entirely different. 

Regarding working together, I have no experience with c++/qt any time soon and your project has no license - how would it be clear what I'm allowed to do?

**Comment by Szybet** [comment]
It's the same thing, just written for diffrent devices

Mine uses Qt, which runs on PC, kobo, remarkable etc. Your is dependent on Remarkable only.

Well you know programming, a language is just a tool. I added a license now ;)

My point is, by porting my app to remarkable, you would achieve your goal of learning with anki and the world would be a better place where people work together to create nicer things, instead of creating 2 almost identical ones...

**Comment by Jayy001** [comment]
I appreciate it, and your app looks really cool 🙂  But my previous point still stands about it being solely dedicated to the remarkable, and I've put in a lot of effort into it already, so no thanks, sorry.
